Copyright (C) "BY ULLA"

YOU CAN USE THIS MOD IN MINETEST, CAN integrate it in other MOD FOR MINETEST, OR OTHERWISE USE EVERYTHING 'IS THIS IN MINETEST MOD, MOD ONLY THIS RESTRICTION AND EVERY PART ORIGINAL CREATED BY ME (MESH, TEXTURES ..) CAN NOT' BE USED FOR PURPOSES publicitari OR OTHER GAMES EXCEPT MY APPROVAL
WITH REGARD TO THE CODE WRITTEN NOTE THE LICENSES MINETEST DEFAULT
EITHER THAT YOU USE IT WILL OF ALL MODE OR SINGLE PARTY THIS LICENSE SHALL BE ENGAGED IN YOUR PROJECT